### ISSUE TITLE
Running on Colmap Data

### ISSUE THREAD

**Issue by g-gaurav** [lioryariv/idr#25]
Thanks for the great work. I was trying to run it on some images captured through my camera. I used the colmap to get the world matrices. But it is giving the following error while trying to run preprocess_camera.py

`preprocess_cameras.py:87: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask_points_all.append(np.stack((xs,ys,np.ones_like(xs))).astype(np.float))
preprocess_cameras.py:45: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  cur_l_1=Fj0 @ np.array([curx,cury,1.0]).astype(np.float)
Number of points:0
preprocess_cameras.py:169: RuntimeWarning: Mean of empty slice.
  centroid = np.array(all_Xs).mean(axis=0)
/home/kshitiz/miniconda3/envs/idr/lib/python3.7/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/home/kshitiz/miniconda3/envs/idr/lib/python3.7/site-packages/numpy/core/_methods.py:263: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims, where=where)
/home/kshitiz/miniconda3/envs/idr/lib/python3.7/site-packages/numpy/core/_methods.py:223: RuntimeWarning: invalid value encountered in true_divide
  subok=False)
/home/kshitiz/miniconda3/envs/idr/lib/python3.7/site-packages/numpy/core/_methods.py:254: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "preprocess_cameras.py", line 244, in <module>
    get_normalization(opt.source_dir, opt.use_linear_init)
  File "preprocess_cameras.py", line 207, in get_normalization
    normalization,all_Xs=get_normalization_function(Ps, mask_points_all, number_of_normalization_points, number_of_cameras,masks_all)
  File "preprocess_cameras.py", line 175, in get_normalization_function
    centroid,scale,all_Xs = refine_visual_hull(masks_all, Ps, scale, centroid)
  File "preprocess_cameras.py", line 101, in refine_visual_hull
    points = points + center[:, np.newaxis]
IndexError: invalid index to scalar variable.`

**Comment by ahnaf1393** [comment]
@g-gaurav were you able to solve the problem? I am facing the same issue.

**Comment by eduardramon** [comment]
Hi @g-gaurav and @ahnaf1393 ! Have you checked if colmap was able to find the correct camera for each image in the scene?

**Comment by ahnaf1393** [comment]
I think they are correct @eduardramon. I will still recheck. By the way, does the origin of the world coordinate system matter in this case? I think for DTU the origin is associated with the robot hand carrying the camera. For me it is the first image that I take with my mobile camera.

**Comment by g-gaurav** [comment]
Hi @eduardramon and @ahnaf1393. Yes, it is working with colmap data. but there is a problem, we need to decide the scale_mat factor. because your object is not on the origin. and scale can be different. so I am not running this preprocessing script. Directly run the training code on the colmap camera matrix and images.

**Comment by ahnaf1393** [comment]
@g-gaurav Don't you need the scal_mat for running the training code? May I ask how you compute it?

**Comment by ghost** [comment]
@g-gaurav Have you solved the problem？

**Comment by siyangbing** [comment]
> @g-gaurav Have you solved the problem？

+1
